---
- name: Configure Kubernetes
  block:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt   
    - name: create .kube directory
      become: yes
      become_user: bot
      file:
        path: $HOME/.kube
        state: directory
        mode: 075
    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/bot/.kube/config
        remote_src: yes
        owner: bot
    # - name: install Pod network
    #   become: yes
    #   shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
    #   args:
    #     chdir: $HOME
    #     creates: pod_network_setup.txt
  become: true